### ISSUE TITLE
Plz help me to use the vscode-box-comment.. I don't know how to load your version to VS code

### ISSUE THREAD

**Issue by Myoontyee** [willasm/emerald-sky#1]
Plz help me to use the vscode-box-comment.. I don't know how to load your version to VS code

I saw your version fix the configuration function and keyshort.

But I don't know how to use the source code of a plugin of VS code

**Comment by willasm** [comment]
I uploaded the vsix package file [emerald-sky-0.0.1.vsix](https://github.com/willasm/emerald-sky/blob/develop/releases/emerald-sky-0.0.1.vsix) You can install the theme with that, just select "Install from vsix..." from the dropdown menu in vscode (click on the 3 dots at the top of the extensions list).

**Comment by willasm** [comment]
I uploaded the vsix package file "emerald-sky-0.0.1.vsix" to
https://github.com/willasm/emerald-sky/blob/develop/releases/emerald-sky-0.0.1.vsix
You can install the theme with that, just select "Install from vsix..."
from the dropdown menu in vscode (click on the 3 dots at the top of the
extensions list).

**Comment by Myoontyee** [comment]
Ohhhh, nice job bro, thanks very much

I have release the .vsix based on your work in the holiday
see [vscode-box-comment-withRelease](https://github.com/Myoontyee/vscode-box-comment-withRelease)
and
[Box Comment修复版Release——Visual Studio Code如何给注释块添加自定义的方框？如何添加带Box的美化注释块？](https://myoontyee.github.io/article/dbacadce.html)
